cp_chain_rpc: "http://127.0.0.1:8545"
cp_chain_id: 31337
cp_chain_starting_height: 1
block_step: 100

oracle_manager_address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
bls_registry_address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
cpusdt_pod_address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"

# Manager 使用账户 0（部署者/聚合者）
private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

manager:
  level_db_folder: "/tmp/oracle/manager_storage"
  ws_addr: "tcp://0.0.0.0:8081"
  http_addr: "127.0.0.1:34567"
  sign_timeout: "5s"
  submit_price_time: "10s"
  # 3 个 Node 的地址
  node_members: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8,0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC,0x90F79bf6EB2c4f870365E785982E1f101E93b906"

node:
  level_db_folder: "/tmp/oracle/node_storage"
  key_path: "/tmp/oracle/bls/key.store"
  ws_addr: "tcp://127.0.0.1:8081"
  sign_timeout: "3s"
  wait_scan_interval: "2s"
  data_source:
    asset_type: "stock"
    asset_name: "Maotai"
    url: "http://127.0.0.1:8888/api/price?symbol=maotai"
    price_path: "data.price"
    decimals: 6
  exchange_config:
    base_http_url: ""
    base_ws_url: ""
