### model
model_name_or_path: ./models/qwen3-4b
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: all

### dataset
dataset_dir: ./data/finetune
dataset: web3_teach_sft
template: qwen3_nothink
cutoff_len: 2048
max_samples: 3000
eval_dataset: web3_teach_sft_eval
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: ./saves/qwen3-4b-web3/lora/sft
logging_steps: 10
save_steps: 100
save_total_limit: 3
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
optim: adamw_torch
ddp_timeout: 180000000
