apiVersion: v1
kind: Namespace
metadata:
  name: protocolbanks
  labels:
    app.kubernetes.io/name: protocolbanks
    app.kubernetes.io/part-of: protocolbanks
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: protocolbanks-quota
  namespace: protocolbanks
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
