[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# 启用优化器和 via-ir 编译模式（解决 Stack too deep 错误）
optimizer = true
optimizer_runs = 200
via_ir = true

fs_permissions = [{ access = "read-write", path = "./" }]

[lint]
lint_on_build = false
severity = [
  'high',
  'med',
  'low',
  # 'info', 'gas', 'codesize'
]
ignore = [
  '**/script/**/*',
  '**/test/**/*',
  "**/lib/**/*",
  # "**/src/**/*",
]
exclude_lints = [
  # "unaliased-plain-import",
]
